export const BASIC_NODE_COMPONENTS = [
  'TargetSearch',
  'ActorWanderBehaviour',
  'Trigger',
  'Timer',
  'StateMachine',
  'Transform',
  'Motion',
  'Graphics',
  'SvgGraphics',
  'Pointer',
  'Actions',
  'Economics',
  'Evolution',
]
